### 
http://localhost:3000/api/pacientes

### Teste de pacientes do nutricionista de id 1
GET http://localhost:3000/api/4/pacientes
Accept: application/json

### Teste de total de pacientes do nutricionista de id 4
GET http://localhost:3000/api/4/total

